server:
  port: 8011
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bankA
    username: root
    password: fflovexx123
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: bank-service-A

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    # database dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    # print sql
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

