server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # disable self-registered
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka