server:
  port: 8022
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource: # second mysql instance deployed on Ali cloud for bankB
    url: jdbc:mysql://47.100.115.68:3323/bankB
    username: root
    password: Mysq1r0Ot135
    driver-class-name: com.mysql.cj.jdbc.Driver


  application:
    name: bank-service-B

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  jpa:
    # database dialect
    database-platform: org.hibernate.dialect.MySQLDialect
    # print sql
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    fetch-registry: false
    registry-fetch-interval-seconds: 30